### ISSUE TITLE
Criar model de vaga

### ISSUE THREAD

**Issue by LucasFelinto** [LucasFelinto/ifparking#10]
Eu como desenvolvedor quero criar o model de vaga para salvar os dados banco de dados.

- [x] Criar model
- [x] Criar seed

**Comment by iBrunoManoel** [comment]
![Table_Zone](https://user-images.githubusercontent.com/49694126/94158953-6186f380-fe59-11ea-8e4a-0ee12b20767b.jpg)

Pra dar uma ajudinha de como vai ser khevin.

**Comment by Khevinn** [comment]
Tive um probleminha com merge, mesmo usando o **git pull origin master** para atualizar o repositório, mas quando fiz o commit ocorreu o merge. Mas já foi corrigido!
