### ISSUE TITLE
Estudar Relacionamento de Entidades 

### ISSUE THREAD

**Issue by Patrick-Santana** [LucasFelinto/ifparking#12]
- Eu como desenvolvedor, irei buscar e compreender, como realizar o relacionamento das entidades do projeto. Utilizando a tecnologia Laravel.

**Comment by ThierryMatheus** [comment]
https://youtu.be/y6NtLvbtDs0 Essa playlist é muito boa, recomendo

**Comment by giovannafernands** [comment]
Para desenvolver e compreender sobre o sistema. Estou estudando sobre o relacionamentos entre modelos laravel.

**Comment by giovannafernands** [comment]
> https://youtu.be/y6NtLvbtDs0 Essa playlist é muito boa, recomendo
