### ISSUE TITLE
Criar CRUD de usuário

### ISSUE THREAD

**Issue by LucasFelinto** [LucasFelinto/ifparking#21]
Eu como usuário quero criar uma conta para poder usar o sistema.

- [x]  Create
- [x] Read
- [x] Update
- [x] Delete

**Comment by ThierryMatheus** [comment]
O Crud de usuário está finalizado, porém as rotas das páginas que eles levam ainda para as rotas padrão do JetStream. Algum front-end de bom coração estiver disposto a organizar isso ficaria emocionado! S2
