### ISSUE TITLE
Estudar MakeFile

### ISSUE THREAD

**Issue by Patrick-Santana** [LucasFelinto/ifparking#4]
- Eu como desenvolvedor, irei descrever os passos necessários para um outro
 desenvolvedor ou usuário técnico, conseguir executar com sucesso o projeto.

- [ ]   Instalação do MySQL e drivers correspondentes ao PDO do MySQL.

- [ ]  Listar Como identificar se o serviço do MySQL está rodando corretamente.

- [ ]  Realizar a instalação do MYSQL  Workbench, como forma de checar a entrada de dados presentes no Banco.

- [x] Realizar a Instalação do Composer

- [x]   E a instalação do Laravel

**Comment by LucasFelinto** [comment]
Vídeo massa sobre makefile, https://www.youtube.com/watch?v=B7ulgCKVnq8

**Comment by giovannafernands** [comment]
Consegui fazer a instalação do laravel e o composer.
