### ISSUE TITLE
Criação do modelo de dados

### ISSUE THREAD

**Issue by LucasFelinto** [LucasFelinto/ifparking#7]
Eu como desenvolvedor quero criar o modelo de dados para definir as entidades do sistema.

**Comment by Patrick-Santana** [comment]
![Modelo](https://user-images.githubusercontent.com/48485663/93947871-44480d00-fd13-11ea-9d0e-b353d12a1ee5.png)

- Modelo Pretendido

**Comment by lilialnas** [comment]
Emocionada

**Comment by ricardomlp** [comment]
![Mod1](https://user-images.githubusercontent.com/42875766/94584588-38010a00-0255-11eb-86e4-eae8cd485949.jpg)

**Comment by ricardomlp** [comment]
Modelo para apreciação. Apenas relações entre entidades.
