### ISSUE TITLE
Criar model de usuário

### ISSUE THREAD

**Issue by LucasFelinto** [LucasFelinto/ifparking#8]
Eu como desenvolvedor quero criar o model de usuário para salvar os dados banco de dados.

- [x] Criar model
- [x] Criar seed

**Comment by Patrick-Santana** [comment]
![Modelo](https://user-images.githubusercontent.com/48485663/93947350-db13ca00-fd11-11ea-958a-dd8772b8ec08.png)

- Modelo Pretendido

**Comment by Patrick-Santana** [comment]
Miguel, Boa noite! model de usuários, criado com sucesso !

**Comment by miguelgabriel01** [comment]
Boa noite meu Rei, a criação da Seeder de users foi criada.

**Comment by Patrick-Santana** [comment]
Okay bolsanaro, os dados estão sendo inseridos com sucesso!
